### PR TITLE
Parallel gripper controller

### LINKED ISSUE #3017: Add missing ParallelGripperCommand controller type
### Description

At some point, ros2_controllers deprecated `position_controllers/GripperActionController` (and its associated action `control_msgs/GripperCommand`), and using it now gives this message:

```
[Deprecated]: the `position_controllers/GripperActionController` and `effort_controllers::GripperActionController` controllers are replaced by 'parallel_gripper_controllers/GripperActionController' controller
```

However, `parallel_gripper_controllers/GripperActionController` uses the action `control_msgs/ParallelGripperCommand`, which has not yet been added to `MoveItSimpleControllerManager`, so trying to use it gives an error.

### ROS Distro

Jazzy

### OS and version

Ubuntu 24.04

### Source or binary build?

Binary

### If binary, which release version?

2.10.0

### If source, which branch?

_No response_

### Which RMW are you using?

FastRTPS

### Steps to Reproduce

Create a `moveit_controllers.yaml` with `type: ParallelGripperCommand`:

```yaml
/**:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - some_controller

      some_controller:
        action_ns: gripper_cmd
        type: ParallelGripperCommand
        default: true
        max_effort: 1000.0
        joints:
          - some_joint
```

### Expected behavior

MoveIt comes up and can command the gripper.

### Actual behavior

MoveIt throws an error and none of the `MoveItSimpleControllerManager` controllers come up.

### Backtrace or Console output

```
[move_group-7] [ERROR] [1727825074.412220666] [move_group.moveit.moveit.plugins.simple_controller_manager]: Unknown controller type: ParallelGripperCommand
```

### PR DESCRIPTION
**Pull request by MarqRazz**
### Description

This PR closes #3017 and adds the option to control grippers that use the ros2_control `ParallelGripperCommand` interface. I renamed all of the existing gripper controller files to include the name `gripper_command` and created new files for the `parallel_gripper_command_controller`.

To setup add the following to your `moveit_controllers.yaml`
```
right_arm_gripper_controller:
  type: ParallelGripperCommand
  joints:
     - right_arm_gripper_joint
  action_ns: gripper_cmd
  allow_stalling: true # optional if you want to pick grasp objects of unknown size and want the request to succeed when the gripper stalls while grasping the object
  max_effort: 1.0 # optional, max effort of the joint allowed while moving (Newtons or Newton-meters)
  max_velocity: 0.5 # optional, max velocity of the joint allowed while moving (radians or meters / second)
  default: true
```

When you start MoveIt you should see the following when adding the controllers
```
[move_group-4] [move_group.moveit.moveit.plugins.simple_controller_manager]: Added ParallelGripperCommand controller for right_arm_gripper_controller
```
parallel_gripper_command_controller

### CODE REVIEW

File: moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp [hunk 1]
```diff
@@ -175,17 +176,57 @@ class MoveItSimpleControllerManager : public moveit_controller_manager::MoveItCo
...
           bool allow_failure;
           node_->get_parameter_or(makeParameterName(PARAM_BASE_NAME, controller_name, "allow_failure"), allow_failure,
                                   false);
-          static_cast<GripperControllerHandle*>(new_handle.get())->allowFailure(allow_failure);
+          static_cast<GripperCommandControllerHandle*>(new_handle.get())->allowFailure(allow_failure);
 
           RCLCPP_INFO_STREAM(getLogger(), "Added GripperCommand controller for " << controller_name);
           controllers_[controller_name] = new_handle;
         }
+        if (type == "ParallelGripperCommand")
```
Comment (mikeferguson) [inline moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp:190]: should this be "else if"?

**Review by mikeferguson — COMMENTED** [review]
I'll take a closer look later today

File: moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp (hunk 1 above)
Comment (MarqRazz) [reply moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp]: Good catch, thanks!

**Review by sea-bass — COMMENTED** [review]
Left some minor comments.

The major comment is a totally new thing that needs to happen here, which is ensuring that this type of controller is included in the MoveIt Setup Assistant.

There's probably a few places in the `moveit_setup_assistant/moveit_setup_controllers` package to edit here -- for example, [this](https://github.com/moveit/moveit2/blob/415a4a2c867bee01a65f1921502350373e4b00ad/moveit_setup_assistant/moveit_setup_controllers/src/ros2_controllers_config.cpp#L195) and [this](https://github.com/moveit/moveit2/blob/415a4a2c867bee01a65f1921502350373e4b00ad/moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/ros2_controllers.hpp#L75)

File: moveit_plugins/moveit_ros_control_interface/src/parallel_gripper_command_controller_plugin.cpp [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+ */
+class ParallelGripperCommandControllerAllocator : public ControllerHandleAllocator
+{
+public:
+  moveit_controller_manager::MoveItControllerHandlePtr alloc(const rclcpp::Node::SharedPtr& node,
+                                                             const std::string& name,
+                                                             const std::vector<std::string>& /* resources */) override
+  {
+    return std::make_shared<moveit_simple_controller_manager::ParallelGripperCommandControllerHandle>(node, name,
+                                                                                                      "gripper_cmd");
```
[the remark this answers is not in the document]
Comment (MarqRazz) [reply moveit_plugins/moveit_ros_control_interface/src/parallel_gripper_command_controller_plugin.cpp:56]: That is actually the namespace of the action and is [hard coded](https://github.com/MarqRazz/ros2_controllers/blob/master/parallel_gripper_controller/include/parallel_gripper_controller/parallel_gripper_action_controller_impl.hpp#L341) in the controller to match the GripperCommand action server.

**Comment by MarqRazz** [comment]
@sea-bass thanks for the detailed review, I appreciate the feedback!

I will try to get to the MSA stuff as soon as I can, but if you are okay to push this off to a different PR then I think this is good to go. I personally don't use the MSA because it makes messy configs.

**Review by sea-bass — APPROVED** [review]
You can do the MSA stuff after -- would definitely wait for @JafarAbdi and @mikeferguson to comment though, since they said they would.

File: moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp [hunk 3]
```diff
@@ -0,0 +1,214 @@
...
+
+  /*
+   * The ``max_velocity_`` used in the ParallelGripperCommand message.
+   */
+  double max_velocity_ = 0.0;
+
+  /*
+   * The joints to command in the ParallelGripperCommand message
+   */
+  std::set<std::string> command_joints_;
```
Comment (JafarAbdi) [inline moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp:211]: Do we actually need to have it as a set? Looking at https://github.com/ros-controls/ros2_controllers/blob/master/parallel_gripper_controller/src/gripper_action_controller_parameters.yaml user can only specify one joint. It will simplify the rest of the code as well. Happy to help with refactoring

File: moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+      finishControllerExecution(wrapped_result.code);
+    }
+  }
+
+  /*
+   * Some gripper drivers may indicate a failure if they do not close all the way when
+   * an object is in the gripper.
+   * If true, this assumes success if the gripper stalls and does not reach the target position goal.
+   */
+  bool allow_stalling_;
```
Comment (JafarAbdi) [inline moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp:196]: Any reason to duplicate this functionality here? The gripper controllers have a parameter to return success after stalling https://github.com/ros-controls/ros2_controllers/blob/master/parallel_gripper_controller/src/gripper_action_controller_parameters.yaml#L29-L46

File: moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp [hunk 5]
```diff
@@ -0,0 +1,214 @@
...
+  void addCommandJoint(const std::string& name)
+  {
+    command_joints_.insert(name);
+  }
+
+  void allowFailure(bool allow)
+  {
+    allow_stalling_ = allow;
+  }
+
```
Comment (JafarAbdi) [inline moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp:175]: Same

File: moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp [hunk 6]
```diff
@@ -0,0 +1,214 @@
...
+      override
+  {
+    if (wrapped_result.code == rclcpp_action::ResultCode::ABORTED && wrapped_result.result->stalled && allow_stalling_)
+    {
+      finishControllerExecution(rclcpp_action::ResultCode::SUCCEEDED);
+    }
+    else
+    {
+      finishControllerExecution(wrapped_result.code);
+    }
```
Comment (JafarAbdi) [inline moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp:188]: If we end up deciding to remove allow_stalling

```suggestion
      return finishControllerExecution(wrapped_result.code);
```

**Review by mikeferguson — APPROVED** [review]

File: moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp (hunk 4 above)
Comment (MarqRazz) [reply moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/parallel_gripper_command_controller_handle.hpp]: Great point I missed that description in the parameters. Removed :+1:

**Review by JafarAbdi — APPROVED** [review]
Thanks!
