### PR TITLE
Fix logic in CheckStartStateBounds adapter

### LINKED ISSUE #2924: CheckStartStateBounds does not support REVOLUTE and NOT Continuous type joints
### Description
CheckStartStateBounds does not support REVOLUTE and NOT Continuous type joints

### Your environment
* ROS Distro: Jazzy
* OS Version: e.g. Ubuntu 24.04
* Binary build 2.10.0

### Steps to reproduce
- Set the initial posture of the actual robot to a position beyond the urdf limit.
- Press “plan” button in rviz to plan the trajectory.

### Expected behaviour
CheckStartStateBounds is not SUCCESS. And fixed to joint limit in case fix_start_state is true.

### Actual behaviour
CheckStartStateBounds is SUCCESS.

### Details

In https://github.com/moveit/moveit2/pull/2429, CheckStartStateBounds is refactored.
The logic has also been changed so that the check is skipped for non-infinite rotation joints, which are used in most arm joints.

https://github.com/moveit/moveit2/blob/a7fe0df4c565db15710581bdcba1d33d70aa0ddb/moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp#L105-L120

### PR DESCRIPTION
**Pull request by sea-bass**
### Description

This PR aims to fix the logic in the `CheckStartStateBounds` adapter, as @chama1176 pointed out.

It also adds some basic unit tests to prevent further breakages and maintain expected behavior.

Closes #2924

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit2/blob/main/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by sea-bass** [comment]
@sjahr I also want to check whether it's intentional that we're not checking the bounds for planar/floating joints at all?

Is this because URDF also doesn't specify limits for this joint type?

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp [hunk 1]
```diff
@@ -115,8 +115,9 @@ class CheckStartStateBounds : public planning_interface::PlanningRequestAdapter
             {
               changed_req = true;
             }
+            break;
           }
-          break;
+          [[fallthrough]];  // If the revolute joint is non-continuous, we want to enter default case.
```
Comment (mikeferguson) [inline moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:120]: don't we need to re-order this so that case REVOLUTE is immediately before the 'default'?

**Comment by mikeferguson** [comment]
Posted this in the issue ticket - but:

The original logic was:

- for each joint model:
  - if REVOLUTE & continuous, call enforceBounds() [OK]
  - else
     - if PLANAR - normalizeRotation [OK]
     - else FLOATING - normalizeRotation [OK]
- read parameters
- for each joint model:
   - apply the satisfiesBounds logic

I think we actually just need to pull the "default" case outside the switch statement and do it for all joints?

**Comment by mikeferguson** [comment]
The fact that this is broken, also makes me think we should really have a test for this... since it seems pretty important to not violate the joint limits in a motion planning software...

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp (hunk 1 above)
Comment (sea-bass) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:120]: Yeah, I think so.

For some reason I thought C++ kept checking the other cases, and not execute them all.

**Comment by sea-bass** [comment]
> The fact that this is broken, also makes me think we should really have a test for this... since it seems pretty important to not violate the joint limits in a motion planning software...

I also didn't look at this... and there are no tests for any of the adapters? Oof. Yeah, I'd like to add one.

**Comment by sea-bass** [comment]
Hah, yeah. It shouldn't be that bad to create a planning scene from e.g. a PR2 or Panda and add some quick tests for the "revolute joint out of bounds" case.

It's more the other paths like continuous joints that will likely require making more robot models.

I'm internally debating how much to bite off here...

**Comment by mikeferguson** [comment]
PR2 has continuous joints in the forearm/wrist roll and it looks like the SRDF in moveit_resources has a planar "world_joint"

**Comment by sea-bass** [comment]
I added some tests and the logic is... more broken than we thought.

@sjahr @mikeferguson do you guys mind lending me a hand w.r.t. what the expected behavior should be?

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp [hunk 2]
```diff
@@ -144,33 +144,36 @@ class CheckStartStateBounds : public planning_interface::PlanningRequestAdapter
...
-                         "the range [%s], [%s].",
-                         jmodel->getName().c_str(), joint_values.str().c_str(), joint_bounds_low.str().c_str(),
-                         joint_bounds_hi.str().c_str());
-          }
+          break;  // do nothing
+        }
+      }
+
+      // Check the joint against its bounds.
+      if (!start_state.satisfiesBounds(jmodel))
```
Comment (sea-bass) [inline moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:152]: Should this condition set `changed_req` to `true` and actually update the start_state variable to be within bounds using `enforceBounds()`?

The old code had this so long as the state was within some specified parameter threshold, which has since been removed.

Comment (mikeferguson) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:152]: There was a discussion in https://github.com/moveit/moveit2/issues/2849

@sjahr stated "In main I replaced the FixStartState adapter in https://github.com/moveit/moveit2/pull/2429 with a simple [CheckStartStateCollision](https://github.com/moveit/moveit2/blob/main/moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_collision.cpp) adapter. My rationale is that an adapter that introduces small jumps is un-intuitive and might lead to undesired behavior, especially given that is was used almost everywhere as a default. I think the decision about what to do when the start state is in collision should be made in a higher level logic than the planning pipeline."

**Comment by mikeferguson** [comment]
So, my understanding (taking into account the notes in 2849) is that, the following should happen:

 * REVOLUTE:
   * continuous - make sure the value is inside the limits (usually +/-pi) - if fix_start_state then basically wrap it, else fail
   * non-continuous - make sure the value is inside the limits - never fix it though (this is the change in behavior from the old days)
 * PLANAR: make sure yaw is normalized - if fix_start_state then fix it, else fail.
 * FLOATING: make sure quaternion rotation is normalized - if fix_start_state then fix it, else fail.

So then, the logic really is:

 - first loop through all joints, check PLANAR, FLOATING, continuous REVOLUTE - figure out how to fix them if needed, then mark 'changed_req' (by the way, this used to be "change_req" before the refactor - not sure why the "d" was added - it's not really past tense when it is set...)
 - important note: when PLANAR, FLOATING or continuous REVOLUTE joints are "change_req" we actually update the `start_state` variable.
 - The call to `start_state.satisifesBounds(jmodel)` will then find non-continuous joints that are invalid (we already updated `start_state` with the fixes above). It looks like we need to add a proper exit here and fail if this isn't true. There is also a huge print statement here - we shouldn't duplicate that, so I think the logic should actually be: `if (!start_state.satisfiesBounds(jmodel) || (change_req && !params.fix_start_state)) { // print and fail }` to catch the case that we need to fix the start state for PLANAR, FLOATING or continuous REVOLUTE.
 - Once we've made it past that now larger if statement, we can simply return success, we're all set...

**Comment by sea-bass** [comment]
That's about in line with what I was thinking. Meaning the doc in the parameters YAML also needs to fixed.

Will wait til Sebastian confirms this behavior and will clean up / fill out the test suite as well.

Thanks!

File: moveit_ros/planning/planning_request_adapter_plugins/test/test_check_start_state_bounds.cpp [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+
+  const auto result = adapter_->adapt(planning_scene_, request);
+  EXPECT_EQ(result.val, moveit_msgs::msg::MoveItErrorCodes::SUCCESS);
+  EXPECT_EQ(result.message, "Changing start state.");
+
+  // Validate that the start state in the request was actually changed.
+  const auto& joint_names = request.start_state.joint_state.name;
+  const size_t joint_idx =
+      std::find(joint_names.begin(), joint_names.end(), "r_forearm_roll_joint") - joint_names.begin();
+  EXPECT_NEAR(request.start_state.joint_state.position[joint_idx], -0.530965, 1.0e-4);
```
Comment (sea-bass) [inline moveit_ros/planning/planning_request_adapter_plugins/test/test_check_start_state_bounds.cpp:156]: this is

```python
>>> import math
>>> math.pi - math.fmod(100.0, math.pi)
0.5309649148733797
```

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp [hunk 4]
```diff
@@ -138,58 +139,60 @@ class CheckStartStateBounds : public planning_interface::PlanningRequestAdapter
...
+
+    if (is_out_of_bounds || (!params.fix_start_state && should_fix_state))
     {
       status.val = moveit_msgs::msg::MoveItErrorCodes::START_STATE_INVALID;
       status.message = std::string("Start state out of bounds.");
     }
-    status.source = getDescription();
+    else if (params.fix_start_state && should_fix_state)
+    {
+      constexpr auto msg_string = "Changing start state.";
```
Comment (mikeferguson) [inline moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:191]: perhaps this should really be "Normalized start state" since that's all we actually change these days?

**Review by mikeferguson — APPROVED** [review]

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp (hunk 2 above)
Comment (sjahr) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:153]: I'd still state that, what do you think?

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp [hunk 5]
```diff
@@ -138,58 +139,60 @@ class CheckStartStateBounds : public planning_interface::PlanningRequestAdapter
...
+      status.message = msg_string;
+      RCLCPP_WARN(logger_, msg_string);
```
Comment (sjahr) [inline moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:193]: Is it duplicate to print + send the status message?

**Review by sjahr — APPROVED** [review]
Thanks for fixing this (and sorry for breaking it :see_no_evil:). My comment's aren't blocking the merge. I think this looks good

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp (hunk 5 above)
Comment (sea-bass) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:193]: Is that because the message is printed by the planning pipeline on failures?

Comment (mikeferguson) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:193]: Most people won't see the status message, but will see the logging. I suppose the status message might be useful for some automated response in downstream user code?

Comment (sea-bass) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:193]: No, I mean it's because the logging happens on the return of the planning adapter here: https://github.com/moveit/moveit2/blob/e7872ebf92146bb80930ec98cf6c181e8384e99c/moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp#L284-L290

Comment (sea-bass) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:193]: ... although in this case it actually won't double print because this warning happens alongside a `SUCCESS` status code. So I think we do want to keep it here.

File: moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp (hunk 2 above)
Comment (sea-bass) [reply moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp:153]: This is fine!

**Review by sjahr — APPROVED** [review]

**Comment by sea-bass** [comment]
Uhh... why is a bunch of new stuff failing suddenly?

Will we ever get some peace in this repo? Lol

**Comment by sea-bass** [comment]
I deleted some GHA caches and the merqe queue jobs seem to be working now. 🤷🏻

**Review by mikeferguson — APPROVED** [review]
